on:
  workflow_run:
    workflows: [unit-tests]
    branches: [main]
    types:
      - completed
jobs:
  depoy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - name: Deploy to S3 action step
        uses: ./.github/actions/action-deploy
        with:
          id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          from: ${{ vars.DEPLOY_FROM }}
          to: ${{ vars.DEPLOY_TO }}
